# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Hawk Eye
tagline:          'Automatic Birds Eye View Registration of Sports Videos'
description:      'Automatic Birds Eye View Registration of Sports Videos'
url:              "https://nihal111.github.io"
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

plugins: [jekyll-gist, jekyll-paginate]